### PR TITLE
Beta5 project json fixes

### PR DESCRIPTION
**Pull request by sblackler**
Resolves the following: #65, #72, #86 

As part of this, I have removed the DNXCORE compile constant that was defined and renamed the places it was used to NETCORE45 which is build it for that platform.

Microsoft.Framework.DependencyInjection is now on Beta6-11427

### CODE REVIEW

**Comment by smudge202** [comment]
Curious. I thought `dotnet` would require nuget dependencies. Are you sure it doesn't? (builds through supporting dnx?)

**Comment by sblackler** [comment]
I would have thought the same, builds locally just fine though. Will clear local copy - re-clone the pr and double check

**Comment by smudge202** [comment]
Instead, try removing all targets other than `dotnet` and make sure it plays nice still? (Prob easier?)

**Comment by sblackler** [comment]
Hmm, interestingly that does fail to build - rather a reference fails to download. It thinks "dotnet" is "dnx451". Same happens on remoting: http://puu.sh/ivmrA/6daf155c6c.png

Leave this open for now, will investigate further. But the core of the work is done at least. Happens on a clean project too: http://puu.sh/ivmR5/7eb295e0c7.png  

Will cc you in dnx room on jabbr

**Comment by sblackler** [comment]
So `dotnet` actually means `im compatible with what ever my dependencies are`: http://oren.codes/2015/06/16/demystifying-pcls-net-core-dnx-and-uwp-redux/

**Comment by smudge202** [comment]
Interesting

**Comment by sblackler** [comment]
I've corrected it to cover all both here and remoting

**Pull request merged**
