### PR TITLE
Core clr

### PR DESCRIPTION
**Pull request by smudge202**
//CC @mattridgway @herecydev @sblackler

### CODE REVIEW

**Comment by smudge202** [comment]
Meh, I suppose I should write the build script too then... That may be later/tomorrow but feel free to branch from here if you want to work on Compose.

**Any PR's branched from dev / using csproj's will be rejected**

**Comment by smudge202** [comment]
@herecydev if you get a chance before I do, can you check out:

Test Name:	ExecutableTests.GivenOnExecuteNotInvokedWhenExecuteAsyncIsInvokedThenThrowsException
Test FullName:	Compose.Tests.ExecutableTests.GivenOnExecuteNotInvokedWhenExecuteAsyncIsInvokedThenThrowsException
Test Source:	D:\Projects\Devbot\Compose\tests\Compose.Tests\ExecutableTests.cs : line 62
Test Outcome:	Failed
Test Duration:	0:00:00.004

Result StackTrace:	
at Xunit.Assert.IsType(Type expectedType, Object object) in C:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.assert\Asserts\TypeAsserts.cs:line 101
   at Xunit.Assert.IsType[T](Object object) in C:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.assert\Asserts\TypeAsserts.cs:line 72
   at Compose.Tests.ExecutableTests.GivenOnExecuteNotInvokedWhenExecuteAsyncIsInvokedThenThrowsException() in D:\Projects\Devbot\Compose\tests\Compose.Tests\ExecutableTests.cs:line 66
Result Message:	
Assert.IsType() Failure
Expected: System.InvalidOperationException
Actual:   System.Threading.Tasks.Task`1[[System.Exception, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]

**Comment by herecydev** [comment]
Will do. Won't be back from jersey till Tuesday though. Looks like a simple enough issue.

**Comment by herecydev** [comment]
Is the .nuspec still needed. I assume almost everything is possible through project.json

**Comment by smudge202** [comment]
Fair point on `nuspec`. I prob need to update project.json to match. Not going to merge this until the build passes, tests run, etc.

**Comment by herecydev** [comment]
Sounds good, there's enough things on this pr that I would do it after as well :D

**Comment by herecydev** [comment]
Exception above fixed by 3d387c6

**Pull request merged**
